In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
inputpath = './input/set-a/'
inputdict = {
    "ALP" : 0,
    "ALT" : 1,
    "AST" : 2,
    "Albumin" : 3,
    "BUN" : 4,
    "Bilirubin" : 5,
    "Cholesterol" : 6,
    "Creatinine" : 7,
    "DiasABP" : 8,
    "FiO2" : 9,
    "GCS" : 10,
    "Glucose" : 11,
    "HCO3" : 12,
    "HCT" : 13,
    "HR" : 14,
    "K" : 15,
    "Lactate" : 16,
    "MAP" : 17,
    "Mg" : 18,
    "Na" : 19,
    "PaCO2" : 20,
    "PaO2" : 21,
    "Platelets" : 22,
    "RespRate" : 23,
    "SaO2" : 24,
    "SysABP" : 25,
    "Temp" : 26,
    "Tropl" : 27,
    "TroponinI" : 27, #temp
    "TropT" : 28,
    "TroponinT" : 28, #temp
    "Urine" : 29,
    "WBC" : 30,
    "Weight" : 31,
    "pH" : 32,
    # addtional. not in the papar
    "NIDiasABP" : 33,
    "NIMAP" : 34,
    "NISysABP" : 35,
    "MechVent" : 36,
    "RecordID" : 37,
    "Age" : 38,
    "Gender" :39,
    "ICUType" : 40,
    "Height": 41
}

In [3]:
def timeparser(time):
    return pd.to_timedelta(time + ':00')

def timedelta_to_day_figure(timedelta):
    return timedelta.days + (timedelta.seconds/86400) #(24*60*60)

In [4]:
def df_to_sum_x(df, x_sum):
    for row_index, value in df.iterrows():
        '''
        0 : values
        1 : # of values observed
        agg_no = row, variable
        '''
        
        #print(value)
        agg_no = inputdict[value.Parameter]
        
        x_sum[agg_no, 0] += value.Value
        x_sum[agg_no, 1] += 1 

    return x_sum

In [5]:
#generate input vectors
x_sum = np.zeros((len(inputdict)-2, 2))

for filename in os.listdir(inputpath):
    df = pd.read_csv(inputpath + filename,\
                     header=0,\
                     parse_dates=['Time'],\
                     date_parser=timeparser)
    x_sum = df_to_sum_x(df, x_sum)
print(x_sum)

[[3.61063000e+05 3.09200000e+03]
 [1.25324700e+06 3.17700000e+03]
 [1.61099600e+06 3.18200000e+03]
 [6.88500000e+03 2.35600000e+03]
 [3.81528400e+05 1.39160000e+04]
 [9.28120000e+03 3.19100000e+03]
 [4.93030000e+04 3.15000000e+02]
 [2.10441000e+04 1.39830000e+04]
 [8.63074200e+06 1.45567000e+05]
 [1.76590750e+04 3.23900000e+04]
 [7.01739000e+05 6.15630000e+04]
 [1.84259600e+06 1.30210000e+04]
 [3.14674600e+05 1.36130000e+04]
 [5.60536800e+05 1.82710000e+04]
 [2.00010612e+07 2.28538000e+05]
 [5.97270000e+04 1.44400000e+04]
 [2.34684300e+04 8.02400000e+03]
 [1.16233290e+07 1.45760000e+05]
 [2.75593000e+04 1.35900000e+04]
 [1.88725900e+06 1.35700000e+04]
 [9.42778300e+05 2.32930000e+04]
 [3.49986247e+06 2.32680000e+04]
 [2.69126490e+06 1.41040000e+04]
 [1.08581100e+06 5.50510000e+04]
 [7.90974400e+05 8.18500000e+03]
 [1.72883490e+07 1.45650000e+05]
 [3.19764610e+06 8.64050000e+04]
 [3.11080000e+03 4.35000000e+02]
 [2.54790700e+03 2.12600000e+03]
 [1.65395203e+07 1.36918000e+05]
 [1.635707

In [6]:
print(x_sum.shape)
print(x_sum)

(42, 2)
[[3.61063000e+05 3.09200000e+03]
 [1.25324700e+06 3.17700000e+03]
 [1.61099600e+06 3.18200000e+03]
 [6.88500000e+03 2.35600000e+03]
 [3.81528400e+05 1.39160000e+04]
 [9.28120000e+03 3.19100000e+03]
 [4.93030000e+04 3.15000000e+02]
 [2.10441000e+04 1.39830000e+04]
 [8.63074200e+06 1.45567000e+05]
 [1.76590750e+04 3.23900000e+04]
 [7.01739000e+05 6.15630000e+04]
 [1.84259600e+06 1.30210000e+04]
 [3.14674600e+05 1.36130000e+04]
 [5.60536800e+05 1.82710000e+04]
 [2.00010612e+07 2.28538000e+05]
 [5.97270000e+04 1.44400000e+04]
 [2.34684300e+04 8.02400000e+03]
 [1.16233290e+07 1.45760000e+05]
 [2.75593000e+04 1.35900000e+04]
 [1.88725900e+06 1.35700000e+04]
 [9.42778300e+05 2.32930000e+04]
 [3.49986247e+06 2.32680000e+04]
 [2.69126490e+06 1.41040000e+04]
 [1.08581100e+06 5.50510000e+04]
 [7.90974400e+05 8.18500000e+03]
 [1.72883490e+07 1.45650000e+05]
 [3.19764610e+06 8.64050000e+04]
 [3.11080000e+03 4.35000000e+02]
 [2.54790700e+03 2.12600000e+03]
 [1.65395203e+07 1.36918000e+05]
 [

In [7]:
x_mean = x_sum[:,:1]/x_sum[:,1:2]

print(x_sum[:,:1])
print(x_sum[:,1:2])

print(x_mean.shape)
print(x_mean)

[[3.61063000e+05]
 [1.25324700e+06]
 [1.61099600e+06]
 [6.88500000e+03]
 [3.81528400e+05]
 [9.28120000e+03]
 [4.93030000e+04]
 [2.10441000e+04]
 [8.63074200e+06]
 [1.76590750e+04]
 [7.01739000e+05]
 [1.84259600e+06]
 [3.14674600e+05]
 [5.60536800e+05]
 [2.00010612e+07]
 [5.97270000e+04]
 [2.34684300e+04]
 [1.16233290e+07]
 [2.75593000e+04]
 [1.88725900e+06]
 [9.42778300e+05]
 [3.49986247e+06]
 [2.69126490e+06]
 [1.08581100e+06]
 [7.90974400e+05]
 [1.72883490e+07]
 [3.19764610e+06]
 [3.11080000e+03]
 [2.54790700e+03]
 [1.65395203e+07]
 [1.63570790e+05]
 [1.07706322e+07]
 [1.82399460e+05]
 [5.69164900e+06]
 [7.43779900e+06]
 [1.16614690e+07]
 [3.11440000e+04]
 [5.50420488e+08]
 [2.56990000e+05]
 [2.24300000e+03]
 [1.10400000e+04]
 [3.55677900e+05]]
[[  3092.]
 [  3177.]
 [  3182.]
 [  2356.]
 [ 13916.]
 [  3191.]
 [   315.]
 [ 13983.]
 [145567.]
 [ 32390.]
 [ 61563.]
 [ 13021.]
 [ 13613.]
 [ 18271.]
 [228538.]
 [ 14440.]
 [  8024.]
 [145760.]
 [ 13590.]
 [ 13570.]
 [ 23293.]
 [ 23268.]
 

In [8]:
x_mean = np.squeeze(x_mean)
print(x_mean.shape)
print(x_mean)

(42,)
[1.16773286e+02 3.94474976e+02 5.06284098e+02 2.92232598e+00
 2.74165277e+01 2.90855531e+00 1.56517460e+02 1.50497747e+00
 5.92905123e+01 5.45201451e-01 1.13987135e+01 1.41509561e+02
 2.31157423e+01 3.06790433e+01 8.75174422e+01 4.13621884e+00
 2.92477941e+00 7.97429267e+01 2.02791023e+00 1.39075829e+02
 4.04747478e+01 1.50415269e+02 1.90815719e+02 1.97237289e+01
 9.66370678e+01 1.18697899e+02 3.70076512e+01 7.15126437e+00
 1.19845108e+00 1.20798728e+02 1.26700844e+01 8.33866153e+01
 7.48919975e+00 5.79538642e+01 7.67804503e+01 1.18594024e+02
 1.00000000e+00 1.37605122e+05 6.42475000e+01 5.60750000e-01
 2.76000000e+00 8.89194750e+01]


In [9]:
x_mean = x_mean[:33]
print(x_mean.shape)
print(x_mean)

(33,)
[116.7732859  394.47497639 506.28409805   2.92232598  27.41652774
   2.90855531 156.51746032   1.50497747  59.29051227   0.54520145
  11.39871351 141.50956148  23.11574231  30.67904329  87.51744218
   4.13621884   2.92477941  79.74292673   2.02791023 139.07582903
  40.47474778 150.41526861 190.81571894  19.72372891  96.63706781
 118.69789907  37.00765118   7.15126437   1.19845108 120.79872844
  12.67008443  83.38661526   7.48919975]


In [10]:
np.save('./input/x_mean', x_mean)
l_x_mean = np.load('./input/x_mean.npy')
print(l_x_mean.shape)
print(l_x_mean)

(33,)
[116.7732859  394.47497639 506.28409805   2.92232598  27.41652774
   2.90855531 156.51746032   1.50497747  59.29051227   0.54520145
  11.39871351 141.50956148  23.11574231  30.67904329  87.51744218
   4.13621884   2.92477941  79.74292673   2.02791023 139.07582903
  40.47474778 150.41526861 190.81571894  19.72372891  96.63706781
 118.69789907  37.00765118   7.15126437   1.19845108 120.79872844
  12.67008443  83.38661526   7.48919975]


In [11]:
x_max = np.load('./input/x_max.npy')
x_nor_mean = l_x_mean / x_max
print(x_nor_mean.shape)
print(x_nor_mean)

(33,)
[0.05295841 0.03439189 0.02747065 0.55138226 0.13917019 0.060976
 0.47429533 0.06809853 0.22123325 0.54520145 0.75991423 0.12380539
 0.46231485 0.49642465 0.29172481 0.18062091 0.09982182 0.26580976
 0.20483942 0.78573915 0.40474748 0.30083054 0.18224997 0.20126254
 0.96637068 0.40236576 0.8790416  0.1453509  0.04811124 0.0109817
 0.06757378 0.27795538 0.01018939]


In [12]:
np.save('./input/x_nor_mean', x_nor_mean)
 
l_x_nor_mean = np.load('./input/x_nor_mean.npy')
print(l_x_nor_mean.shape)
print(l_x_nor_mean)

(33,)
[0.05295841 0.03439189 0.02747065 0.55138226 0.13917019 0.060976
 0.47429533 0.06809853 0.22123325 0.54520145 0.75991423 0.12380539
 0.46231485 0.49642465 0.29172481 0.18062091 0.09982182 0.26580976
 0.20483942 0.78573915 0.40474748 0.30083054 0.18224997 0.20126254
 0.96637068 0.40236576 0.8790416  0.1453509  0.04811124 0.0109817
 0.06757378 0.27795538 0.01018939]
