In [1]:
import numpy as np
import pandas as pd
import os

In [7]:
A_outcome = pd.read_csv('./input/Outcomes-a.txt')
#print(A_outcome)

In [8]:
arr_outcome = A_outcome.values
print(arr_outcome)

[[132539      6      1      5     -1      0]
 [132540     16      8      8     -1      0]
 [132541     21     11     19     -1      0]
 ...
 [142670      8      5     11     -1      0]
 [142671     22     10      8      7      1]
 [142673     25     11      7     -1      0]]


In [9]:
out_max = np.amax(arr_outcome, axis=0)
print(out_max)

[142673     34     22    154   2600      1]


In [10]:
nor_outcomes = arr_outcome/out_max[np.newaxis, :]
print(nor_outcomes)

[[ 9.28970443e-01  1.76470588e-01  4.54545455e-02  3.24675325e-02
  -3.84615385e-04  0.00000000e+00]
 [ 9.28977452e-01  4.70588235e-01  3.63636364e-01  5.19480519e-02
  -3.84615385e-04  0.00000000e+00]
 [ 9.28984461e-01  6.17647059e-01  5.00000000e-01  1.23376623e-01
  -3.84615385e-04  0.00000000e+00]
 ...
 [ 9.99978973e-01  2.35294118e-01  2.27272727e-01  7.14285714e-02
  -3.84615385e-04  0.00000000e+00]
 [ 9.99985982e-01  6.47058824e-01  4.54545455e-01  5.19480519e-02
   2.69230769e-03  1.00000000e+00]
 [ 1.00000000e+00  7.35294118e-01  5.00000000e-01  4.54545455e-02
  -3.84615385e-04  0.00000000e+00]]


In [11]:
s_nor_outcomes = nor_outcomes[:,1:]
print(s_nor_outcomes)

s_out_max = out_max[1:]
print(s_out_max)

[[ 1.76470588e-01  4.54545455e-02  3.24675325e-02 -3.84615385e-04
   0.00000000e+00]
 [ 4.70588235e-01  3.63636364e-01  5.19480519e-02 -3.84615385e-04
   0.00000000e+00]
 [ 6.17647059e-01  5.00000000e-01  1.23376623e-01 -3.84615385e-04
   0.00000000e+00]
 ...
 [ 2.35294118e-01  2.27272727e-01  7.14285714e-02 -3.84615385e-04
   0.00000000e+00]
 [ 6.47058824e-01  4.54545455e-01  5.19480519e-02  2.69230769e-03
   1.00000000e+00]
 [ 7.35294118e-01  5.00000000e-01  4.54545455e-02 -3.84615385e-04
   0.00000000e+00]]
[  34   22  154 2600    1]


In [12]:
np.save('./input/max_out', s_out_max)
np.save('./input/nor_out', s_nor_outcomes)

l_max = np.load('./input/max_out.npy')
l_out = np.load('./input/nor_out.npy')

print(l_max.shape)
print(l_out.shape)

(5,)
(4000, 5)
